version: '3.8'
services:
    e-commerce:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8002:8000
        volumes:
            - .:/app
        depends_on:
            - e-commerce-db
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        networks:
            - app-network
        command: sh -c "php artisan migrate &&  php artisan db:seed &&  php artisan serve --host=0.0.0.0"

    e-commerce-db:
        image: mysql:5.7.22
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: e-commerce
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456789
            MYSQL_ROOT_PASSWORD: 123456789
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33063:3306
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: e-commerce-db
            PMA_USER: root
            PMA_PASSWORD: 123456789
        ports:
            - "8086:80"
        depends_on:
            - e-commerce-db
        networks:
            - app-network

    redis:
        image: redis:latest
        ports:
            - "6380:6379"
        volumes:
            - redis-data:/data
        command: redis-server --appendonly yes
        networks:
            - app-network

volumes:
    redis-data:

networks:
    app-network:
        driver: bridge
